// PDF report of a registry, downloaded from the office console (supervisor only).

import type { DocumentReport } from "../../shared/messages.ts";

const filename = (report: DocumentReport) => `maternily-report-${report.documentId.slice(0, 8)}.pdf`;

export async function createReportPdf(report: DocumentReport, lang: "fr" | "en"): Promise<File> {
  const { jsPDF } = await import("jspdf");
  const pdf = new jsPDF({ format: "a4", unit: "mm" });
  const left = 16;
  const right = 194;
  const bottom = 280;
  let y = 18;

  const write = (text: string, options: { bold?: boolean; size?: number; gap?: number } = {}) => {
    const size = options.size ?? 10;
    pdf.setFont("helvetica", options.bold ? "bold" : "normal");
    pdf.setFontSize(size);
    const lines = pdf.splitTextToSize(text, right - left) as string[];
    for (const line of lines) {
      if (y > bottom) {
        pdf.addPage();
        y = 18;
      }
      pdf.text(line, left, y);
      y += size * 0.42;
    }
    y += options.gap ?? 2;
  };

  write("Maternily", { bold: true, size: 20, gap: 1 });
  write(lang === "fr" ? "Rapport de lecture du registre" : "Registry reading report", { bold: true, size: 14 });
  write(`${new Date(report.createdAt).toLocaleString(lang)} · ${report.pageCount} ${lang === "fr" ? "page(s)" : "page(s)"}`);

  write(lang === "fr" ? "Pages traitées" : "Pages processed", { bold: true, size: 12, gap: 1 });
  for (const page of report.pages) {
    write(`${lang === "fr" ? "Page" : "Page"} ${page.number} · ${page.section} · ${page.state}`);
    for (const issue of page.issues) write(`  ${lang === "fr" ? "À vérifier" : "Check"}: ${issue}`);
  }

  write(lang === "fr" ? "Valeurs extraites" : "Extracted values", { bold: true, size: 12, gap: 1 });
  if (!report.fields.length) write(lang === "fr" ? "Aucune valeur extraite." : "No values were extracted.");
  for (const field of report.fields) {
    const page = field.pageNo === null ? "" : ` · p. ${field.pageNo}`;
    write(`${field.label}: ${field.value || (lang === "fr" ? "Non renseigné" : "Not provided")}${page}`, { bold: true, gap: 0 });
    write(`${field.status} · ${lang === "fr" ? "confiance" : "confidence"} ${Math.round(field.confidence * 100)}%`);
    for (const reason of field.reasons) write(`  ${lang === "fr" ? "À vérifier" : "Check"}: ${reason}`);
  }

  write(
    lang === "fr"
      ? "Rapport généré par Maternily. Les valeurs incertaines sont signalées; vérifiez le document source avant toute utilisation clinique."
      : "Generated by Maternily. Uncertain values are flagged; check the source document before clinical use.",
    { size: 8, gap: 0 },
  );
  return new File([pdf.output("blob")], filename(report), { type: "application/pdf" });
}

export function downloadReport(file: File) {
  const url = URL.createObjectURL(file);
  const link = document.createElement("a");
  link.href = url;
  link.download = file.name;
  link.click();
  window.setTimeout(() => URL.revokeObjectURL(url), 30_000);
}
